from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Tuple

from app.domain.entities import ReportMeta


class ScannerPort(Protocol):
    is_connected: bool

    def set_manufacturer(self, manufacturer: str) -> None: ...
    def set_raw_logger(self, logger: Optional[Any]) -> None: ...
    def set_port(self, port: str) -> None: ...
    def connect(self) -> bool: ...
    def disconnect(self) -> None: ...
    def get_transport(self) -> Any: ...
    def debug_snapshot(self) -> Dict[str, Any]: ...
    def get_vehicle_info(self) -> Dict[str, Any]: ...
    def read_dtcs(self) -> List[Dict[str, Any]]: ...
    def read_readiness(self) -> Dict[str, Any]: ...
    def read_live_data(self, pids: Optional[List[str]] = None) -> Dict[str, Any]: ...
    def read_freeze_frame(self) -> Dict[str, Any]: ...
    def clear_codes(self) -> bool: ...


class KLineScannerPort(Protocol):
    is_connected: bool
    is_kline: bool

    def set_manufacturer(self, manufacturer: str) -> None: ...
    def set_raw_logger(self, logger: Optional[Any]) -> None: ...
    def disconnect(self) -> None: ...
    def read_dtcs(self, mode: str = "stored") -> Dict[str, Any]: ...
    def clear_dtcs(self) -> Tuple[bool, Dict[str, Any]]: ...
    def read_pid(self, pid: str) -> Dict[str, Any]: ...


class ScannerFactory(Protocol):
    def create(self, manufacturer: Optional[str]) -> ScannerPort: ...


class KLineScannerFactory(Protocol):
    def create(self, port: str, manufacturer: Optional[str]) -> KLineScannerPort: ...
    def detect(self, port: str, manufacturer: Optional[str], raw_logger: Optional[Any] = None) -> Tuple[Optional[KLineScannerPort], Optional[Dict[str, Any]], Optional[Exception]]: ...


class PortsScanner(Protocol):
    def scan_usb_ports(self) -> List[str]: ...
    def scan_ble_devices(
        self, include_all: bool = False, timeout_s: Optional[float] = None
    ) -> Tuple[List[Tuple[str, str, int]], Optional[str]]: ...
    def try_connect(self, scanner: ScannerPort, port: str) -> Tuple[bool, Dict[str, Any], Optional[Exception]]: ...


class DtcLookupPort(Protocol):
    def lookup(self, code: str) -> Optional[Dict[str, Any]]: ...
    def search(self, text: str) -> List[Dict[str, Any]]: ...
    def set_manufacturer(self, manufacturer: str) -> None: ...


class DtcDatabaseFactory(Protocol):
    def create(self, manufacturer: Optional[str]) -> DtcLookupPort: ...


class RawLoggerFactory(Protocol):
    def create(self, enabled: bool) -> Optional[Any]: ...


class VinDecoderPort(Protocol):
    def decode_vpic(self, vin: str, model_year: Optional[str] = None) -> Optional[Dict[str, Any]]: ...


class AiReportPort(Protocol):
    def decode_vin(self, vin: str, manufacturer: str) -> Optional[Dict[str, Any]]: ...
    def request_report(self, report_input: Dict[str, Any], language: str) -> str: ...


class AiConfigPort(Protocol):
    def get_api_key(self) -> Optional[str]: ...
    def get_model(self) -> str: ...


class PaywallPort(Protocol):
    def is_configured(self) -> bool: ...
    def is_bypass_enabled(self) -> bool: ...
    def api_base(self) -> Optional[str]: ...
    def set_api_base(self, api_base: str) -> None: ...
    def subject_id(self) -> Optional[str]: ...
    def cached_balance(self) -> Optional[Tuple[int, int]]: ...
    def get_balance(self) -> Any: ...
    def pending_total(self) -> int: ...
    def ensure_identity(self) -> Any: ...
    def consume(self, action: str, cost: int = 1) -> Any: ...
    def checkout(self) -> str: ...
    def wait_for_balance(self, *, min_paid: int = 1, timeout_seconds: int = 120) -> Any: ...
    def reset_identity(self) -> None: ...


class ReportRepository(Protocol):
    def save_report(self, payload: Dict[str, Any]) -> str: ...
    def list_reports(self) -> List[ReportMeta]: ...
    def load_report(self, path: str) -> Dict[str, Any]: ...
    def find_report_by_id(self, report_id: str) -> Optional[str]: ...
    def write_report(self, path: str, payload: Dict[str, Any]) -> None: ...


class FullScanReportRepository(Protocol):
    def save(self, lines: List[str]) -> str: ...
    def list(self) -> List[str]: ...
    def load(self, path: str) -> str: ...


class SettingsRepository(Protocol):
    def load(self) -> Dict[str, Any]: ...
    def save(self, settings: Dict[str, Any]) -> None: ...


class VinCacheRepository(Protocol):
    def get(self, vin: str) -> Optional[Dict[str, Any]]: ...
    def set(self, vin: str, profile: Dict[str, Any]) -> None: ...


class PdfRendererPort(Protocol):
    def render(
        self,
        payload: Dict[str, Any],
        output_path: str,
        *,
        report_json: Optional[Dict[str, Any]] = None,
        report_text: Optional[str] = None,
        language: Optional[str] = None,
    ) -> None: ...


class PdfPathPort(Protocol):
    def report_pdf_path(self, report_id: str) -> str: ...


class DocumentPathPort(Protocol):
    def ai_report_pdf_path(self, vehicle_payload: Dict[str, Any]) -> str: ...


class DataPathPort(Protocol):
    def raw_log_path(self) -> str: ...


class I18nRepository(Protocol):
    def load_all(self) -> Dict[str, Dict[str, Any]]: ...


class UdsDiscoveryPort(Protocol):
    def discover(self, scanner: ScannerPort, options: Dict[str, Any]) -> Dict[str, Any]: ...


class UdsClientPort(Protocol):
    def read_did(self, brand: str, did: str) -> Dict[str, Any]: ...
    def send_raw(self, service_id: int, data: bytes, *, raise_on_negative: bool = False) -> bytes: ...


class UdsClientFactory(Protocol):
    def create(self, transport: Any, brand: str, module_entry: Dict[str, Any]) -> UdsClientPort: ...
    def module_map(self, brand: str) -> Dict[str, Dict[str, str]]: ...


class TelemetryLoggerPort(Protocol):
    def start_session(self, format: str = "csv") -> str: ...
    def log_readings(self, readings: Dict[str, Any]) -> None: ...
    def end_session(self) -> Dict[str, Any]: ...


class TelemetryLoggerFactory(Protocol):
    def create(self) -> TelemetryLoggerPort: ...
